### ISSUE TITLE
Support all ClickableSpans, not just URLSpan.

### ISSUE THREAD

**Issue by JakeWharton** [Saketme/Better-Link-Movement-Method#1]
As far as I can tell there's no reason to only support `URLSpan` when `ClickableSpan`s are commonly used for non-URL linking inside text.

**Comment by Saketme** [comment]
_Whoa, it's JakeWharton! Alright, calm down. Stop smiling. Act normal._

The reason I chose not to use `ClickableSpan` was because it does not provide any method to get the span's URL. In comparison, `URLSpan` has `getURL()` which makes the job really easy.

@madhu314 has proposed a solution in #2 that basically falls back to scraping the span's text if `URLSpan` wasn't found as the link. What do you think? :)

**Comment by JakeWharton** [comment]
Actually I'm not a big fan of your callback which passes in the URL. Both `URLSpan` and `ClickableSpan` have an `onClick(View)` method that can be invoked. This is the standard way to specify custom clicked behavior of a either of these spans so really all I care about is that it gets invoked.

**Comment by Saketme** [comment]
Interesting. I extracted this library from another personal project where I wanted to listen to URL clicks in TextViews across the app and this looked like the easiest way. 

The only other option I could come up with was replacing all spans inserted by `Linkify` with custom spans (with overriden `onClick()`), but that did not feel like an optimized solution.

Would you have solved this problem in any other way?

**Comment by JakeWharton** [comment]
I've never used `Linkify`, but I suppose the approach makes sense. I'm solely using `ClickableSpan` and not using URLs for anything which requires the different approach I described.

**Comment by Saketme** [comment]
Alright, merging #2 then. Thanks for contributing, @JakeWharton.
